name: Rust publish

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CARGO_API_TOKEN: ${{ secrets.CARGO_API_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --token $CARGO_API_TOKEN