name: Rust publish

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CARGO_API_TOKEN: ${{ secrets.CARGO_API_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: Publish rudp2p
        run: cargo publish -p rudp2p --token $CARGO_API_TOKEN
      - name: Publish rudp2p_derive
        run: cargo publish -p rudp2p_derive --token $CARGO_API_TOKEN
