name: Rust tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Prepare tests
        run: docker-compose -f tests/compose.yml up -d
      - name: Run tests with default features
        run: cargo test
      - name: Run tests with feature "mysql"
        run: cargo test --features="mysql" --no-default-features
      - name: Run tests with features "sqlite", "ssl"
        run: cargo test --features="sqlite,ssl" --no-default-features
      - name: Run tests with features "mysql", "ssl"
        run: cargo test --features="mysql,ssl" --no-default-features
      - name: Clear tests
        run: docker-compose -f tests/compose.yml down
      - name: Push reports
        if: github.ref_name != 'master'
        run: |
          git config --local user.name "GitHub Action [bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config advice.addIgnoredFile false
          git add -f reports
          git commit -m "Add cucumber reports"
          git push -f origin HEAD:refs/heads/${{ github.head_ref }}
