name: Rust tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3

      - name: Prepare tests
        run: docker-compose -f tests/compose.yml up -d

      - name: Build
        run: cargo build --verbose

      - name: Compatibility WASM
        working-directory: ./wasm
        run: cargo build --lib --target wasm32-unknown-unknown

      - name: Run tests with default features
        run: cargo test

      - name: Run tests with feature ""ssl"
        run: cargo test --features="ssl"
        
      - name: Clear tests
        run: docker-compose -f tests/compose.yml down

      - name: Push reports
        if: github.ref_name != 'master'
        run: |
          git config --local user.name "GitHub Action [bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config advice.addIgnoredFile false
          git add -f reports/default.md reports/ssl.md
          git commit -m "Add cucumber reports"
          git push -f origin HEAD:refs/heads/${{ github.head_ref }}
