name: Rust tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare tests
        run: docker-compose -f rudp2p/tests/compose.yml up -d

      - name: Build
        run: cargo build --verbose

      - name: Compatibility WASM
        run: |
          rustup target add wasm32-unknown-unknown
          cargo build --lib --target wasm32-unknown-unknown

      - name: Run tests
        working-directory: ./rudp2p
        run: |
          cargo test
          cargo test --features="ssl"
        
      - name: Clear tests
        run: docker-compose -f rudp2p/tests/compose.yml down

      - name: Push reports
        if: github.ref_name != 'master'
        run: |
          git config --local user.name "GitHub Action [bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config advice.addIgnoredFile false
          git add -f reports/default.md reports/ssl.md
          git commit -m "Add cucumber reports"
          git push -f origin HEAD:refs/heads/${{ github.head_ref }}
