name: Rust tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --test peer
      - name: Update README
        run: |
          bash generate_readme.sh
          modifs=$(git status --porcelain | grep README | wc -l)
          if [ $modifs != 0 ]; then
            git config --local user.name "GitHub Action [bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Update README"
            git push origin master
          fi
